GHA publish test reports (#26)
* GHA publish test reports

* Apply suggestion from @perok

* Apply suggestion from @perok

* Apply suggestion from @perok

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -70,6 +70,13 @@ jobs:
           - name: Test
             run: sbt 'fh-datastar-view/testFull'
 
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/**/test-reports/*.xml'
+          require_tests: true
+
       - name: Assemble fat jar
         run: sbt 'fh-datastar-view/assembly'
 
